In [3]:
%pip install --upgrade pandas bottleneck openpyxl

Requirement already satisfied: pandas in c:\users\juank\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: bottleneck in c:\users\juank\anaconda3\lib\site-packages (1.3.5)
Collecting bottleneck
  Downloading bottleneck-1.5.0-cp311-cp311-win_amd64.whl (112 kB)
                                              0.0/112.1 kB ? eta -:--:--
     -------------------------------------- 112.1/112.1 kB 6.4 MB/s eta 0:00:00
Requirement already satisfied: openpyxl in c:\users\juank\anaconda3\lib\site-packages (3.0.10)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
                                              0.0/250.9 kB ? eta -:--:--
     ------------------------------------- 250.9/250.9 kB 16.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.23.2 in c:\users\juank\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\juank\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\juank\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: tzdata>=2022.7 in c:\users\juank\anaconda3\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: et-xmlfile in c:\users\juank\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\users\juank\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: openpyxl, bottleneck
  Attempting uninstall: openpyxl
    Found existing installation: openpyxl 3.0.10
    Uninstalling openpyxl-3.0.10:
      Successfully uninstalled openpyxl-3.0.10
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: [WinError 5] Acceso denegado: 'C:\\Users\\juank\\anaconda3\\Lib\\site-packages\\~penpyxl\\utils\\cell.cp311-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [1]:
import pandas as pd
import numpy as np

c:\Users\juank\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [ ]:
df = pd.read_excel("base_total.xlsx", engine="openpyxl")
df = df.convert_dtypes()

c:\Users\juank\anaconda3\Lib\site-packages\pandas\core\dtypes\cast.py:1056: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():
c:\Users\juank\anaconda3\Lib\site-packages\pandas\core\dtypes\cast.py:1080: RuntimeWarning: invalid value encountered in cast
  if (arr.astype(int) == arr).all():

ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column genero with type object')

In [6]:

df.head(100)

,Corte,id_pol,dias_mora,Estado_Inicial,Plan_Agrupado,Ant_pol,NBS,Rehabilitada,Huerfano,MedioPago,...,Total_Activas,NBS_Vigente,Freceuncia_Pago,estado_Final_pol,Validacion_Mora,Estado_final_3_meses_atras,Estado_Final_2_meses_atras,Estado_Final_1_mes_despues,Estado_Final_2_meses_despues,Estado_Final_4_meses_despues
0,2025-01-01,1,17,3.Mora <=30,Vida Entera,317,1198163,<NA>,1,PAGO DIRECTO,...,1,1198163,MENSUAL,VIG,1,<NA>,1.Al dia,1.Al dia,3.Mora <=30,3.Mora <=30
1,2025-01-01,2,-29,1.Al dia,Temporal,290,1056296,<NA>,<NA>,MASTER CARD,...,2,1774282,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
2,2025-01-01,3,-22,1.Al dia,AP,314,364493,<NA>,1,DESCUENTO DE NOMINA,...,3,5250399,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
3,2025-01-01,4,-14,1.Al dia,AP,299,696918,<NA>,1,DEBITO A CUENTAS ACH,...,1,662470,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
4,2025-01-01,5,0,1.Al dia,AP,295,695639,<NA>,<NA>,VISA,...,1,695639,MENSUAL,VIG,0,<NA>,1.Al dia,1.Al dia,<NA>,1.Al dia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2025-01-01,86,-23,1.Al dia,AP,261,1624215,<NA>,1,BANCOLOMBIA DEB AUTO,...,1,1624215,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
96,2025-01-01,87,-24,1.Al dia,AP,261,985292,<NA>,1,DESCUENTO DE NOMINA,...,2,5472289,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,3.Mora <=30
97,2025-01-01,88,-3,1.Al dia,AP,260,1651814,<NA>,1,VISA,...,2,2067160,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
98,2025-01-01,89,-27,1.Al dia,AP,260,1237825,<NA>,1,PAGO DIRECTO,...,1,1237825,MENSUAL,VIG,0,3.Mora <=30,1.Al dia,2.Pendiente_Mes,1.Al dia,1.Al dia
99,2025-01-01,90,-13,1.Al dia,AP,260,861096,<NA>,1,MASTER CARD,...,7,16650306,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia

In [7]:
df.shape

(873410, 33)

In [24]:
filtered = df[df["Corte"].dt.normalize() == pd.Timestamp("2025-01-01") ].copy()

In [28]:
filtered.rename(columns={'Freceuncia_Pago':'frecuencia_pago'}, inplace= True)
filtered = filtered[filtered['frecuencia_pago'] == 'MENSUAL']

filtered.head()

,Corte,id_pol,dias_mora,Estado_Inicial,Plan_Agrupado,Ant_pol,NBS,Rehabilitada,Huerfano,MedioPago,...,Total_Activas,NBS_Vigente,frecuencia_pago,estado_Final_pol,Validacion_Mora,Estado_final_3_meses_atras,Estado_Final_2_meses_atras,Estado_Final_1_mes_despues,Estado_Final_2_meses_despues,Estado_Final_4_meses_despues
0,2025-01-01,1,17,3.Mora <=30,Vida Entera,317,1198163,<NA>,1,PAGO DIRECTO,...,1,1198163,MENSUAL,VIG,1,<NA>,1.Al dia,1.Al dia,3.Mora <=30,3.Mora <=30
1,2025-01-01,2,-29,1.Al dia,Temporal,290,1056296,<NA>,<NA>,MASTER CARD,...,2,1774282,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
2,2025-01-01,3,-22,1.Al dia,AP,314,364493,<NA>,1,DESCUENTO DE NOMINA,...,3,5250399,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
3,2025-01-01,4,-14,1.Al dia,AP,299,696918,<NA>,1,DEBITO A CUENTAS ACH,...,1,662470,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
4,2025-01-01,5,0,1.Al dia,AP,295,695639,<NA>,<NA>,VISA,...,1,695639,MENSUAL,VIG,0,<NA>,1.Al dia,1.Al dia,<NA>,1.Al dia

In [29]:
filtered.shape

(109115, 33)

In [18]:
filtered.isna().sum()

Corte                                   0
id_pol                                  0
dias_mora                               0
Estado_Inicial                          0
Plan_Agrupado                           0
Ant_pol                                 0
NBS                                     0
Rehabilitada                       109109
Huerfano                            58750
MedioPago                               6
garantizado                        109666
Prestamos                          110936
Ant_consultor_original              14367
Ant_consultor_original_retirado     64185
Agencia_Original                    14369
ingresos                               40
egresos                                40
activos                                40
genero                                 40
Edad                                   40
Juridico                                0
total_mora                              0
NBS_mORA                                0
Total_Activas                          10
NBS_Vigente                            10
Freceuncia_Pago                      1103
estado_Final_pol                        0
Validacion_Mora                         0
Estado_final_3_meses_atras           9622
Estado_Final_2_meses_atras           5702
Estado_Final_1_mes_despues           2854
Estado_Final_2_meses_despues         6457
Estado_Final_4_meses_despues         6775
dtype: int64

In [32]:
filtered["MedioPago"].value_counts(dropna=False)

MedioPago
VISA                    25462
BANCOLOMBIA DEB AUTO    24592
MASTER CARD             23436
DEBITO A CUENTAS ACH    17905
DESCUENTO DE NOMINA      5718
PAGO DIRECTO             4892
CUENTAS BBVA             2720
AMERICAN EXPRESS         2292
COSTUMER ENGAGEMENT      1270
DINERS                    667
CREDENCIAL                133
SINIESTROS                  9
CANCELACIONES               9
<NA>                        6
DAVIVIENDA DEB AUT          1
VISA IMD                    1
DINERS IMD                  1
MASTERCARD IMD              1
Name: count, dtype: Int64

Quitar medios de pago de productos diferentes

In [33]:
filtered = filtered[(~ filtered["MedioPago"].isin(["CANCELACIONES","SINIESTROS","COSTUMER ENGAGEMENT"])) & filtered["MedioPago"].notna()]

In [34]:
filtered["MedioPago"].value_counts(dropna=False)

MedioPago
VISA                    25462
BANCOLOMBIA DEB AUTO    24592
MASTER CARD             23436
DEBITO A CUENTAS ACH    17905
DESCUENTO DE NOMINA      5718
PAGO DIRECTO             4892
CUENTAS BBVA             2720
AMERICAN EXPRESS         2292
DINERS                    667
CREDENCIAL                133
DAVIVIENDA DEB AUT          1
VISA IMD                    1
DINERS IMD                  1
MASTERCARD IMD              1
Name: count, dtype: Int64

In [35]:
filtered["MedioPago"] = np.where(filtered["MedioPago"] == "PAGO DIRECTO", "MANUAL", "AUTOMATICO")

In [36]:
filtered["MedioPago"].value_counts(dropna=False)

MedioPago
AUTOMATICO    102929
MANUAL          4892
Name: count, dtype: int64

In [38]:
filtered.columns

Index(['Corte', 'id_pol', 'dias_mora', 'Estado_Inicial', 'Plan_Agrupado',
       'Ant_pol', 'NBS', 'Rehabilitada', 'Huerfano', 'MedioPago',
       'garantizado', 'Prestamos', 'Ant_consultor_original',
       'Ant_consultor_original_retirado', 'Agencia_Original', 'ingresos',
       'egresos', 'activos', 'genero', 'Edad', 'Juridico', 'total_mora',
       'NBS_mORA', 'Total_Activas', 'NBS_Vigente', 'frecuencia_pago',
       'estado_Final_pol', 'Validacion_Mora', 'Estado_final_3_meses_atras',
       'Estado_Final_2_meses_atras', 'Estado_Final_1_mes_despues',
       'Estado_Final_2_meses_despues', 'Estado_Final_4_meses_despues'],
      dtype='object')

Eliminar ids duplicados, como no podemos saber cual es el registro correcto se eliminan ambos (138 filas)

In [58]:
filtered.shape

(107821, 33)

In [57]:
filtered[filtered.duplicated(subset="id_pol", keep = False)].sort_values(by="id_pol")

,Corte,id_pol,dias_mora,Estado_Inicial,Plan_Agrupado,Ant_pol,NBS,Rehabilitada,Huerfano,MedioPago,...,Total_Activas,NBS_Vigente,frecuencia_pago,estado_Final_pol,Validacion_Mora,Estado_final_3_meses_atras,Estado_Final_2_meses_atras,Estado_Final_1_mes_despues,Estado_Final_2_meses_despues,Estado_Final_4_meses_despues
7,2025-01-01,8,-24,1.Al dia,AP,292,748856,<NA>,1,AUTOMATICO,...,2,1529849,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,3.Mora <=30
33,2025-01-01,8,-24,1.Al dia,AP,292,748856,<NA>,1,AUTOMATICO,...,2,1529849,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,3.Mora <=30
8,2025-01-01,9,-16,1.Al dia,AP,291,969307,<NA>,1,AUTOMATICO,...,2,1522044,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
36,2025-01-01,9,-16,1.Al dia,AP,291,969307,<NA>,1,AUTOMATICO,...,2,1522044,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
14,2025-01-01,15,-20,1.Al dia,AP,284,747428,<NA>,1,AUTOMATICO,...,3,1728421,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92406,2025-01-01,92315,-20,1.Al dia,Vida Entera,70,8262826,<NA>,1,AUTOMATICO,...,6,25545369,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
97300,2025-01-01,97206,-30,1.Al dia,Temporal,144,1035335,<NA>,1,AUTOMATICO,...,4,8035304,MENSUAL,VIG,0,1.Al dia,1.Al dia,3.Mora <=30,4.Mora <=60,3.Mora <=30
97299,2025-01-01,97206,-30,1.Al dia,Temporal,144,1035335,<NA>,1,AUTOMATICO,...,4,8035304,MENSUAL,VIG,0,1.Al dia,1.Al dia,3.Mora <=30,4.Mora <=60,3.Mora <=30
107105,2025-01-01,107006,-4,1.Al dia,Temporal,28,4450249,<NA>,<NA>,AUTOMATICO,...,4,15417674,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia
107106,2025-01-01,107006,-4,1.Al dia,Temporal,28,4450249,<NA>,<NA>,AUTOMATICO,...,4,15417674,MENSUAL,VIG,0,1.Al dia,1.Al dia,1.Al dia,1.Al dia,1.Al dia

In [59]:
filtered.drop_duplicates(subset="id_pol", keep=False, inplace=True)

Polizas con 6 meses o mas

In [67]:
filtered = filtered[filtered['Ant_pol'] >= 6]

In [69]:
filtered.shape

(98037, 33)

Eliminar columnas innecesarias

In [73]:
filtered.columns

Index(['Corte', 'id_pol', 'dias_mora', 'Estado_Inicial', 'Plan_Agrupado',
       'Ant_pol', 'NBS', 'Rehabilitada', 'Huerfano', 'MedioPago',
       'garantizado', 'Prestamos', 'Ant_consultor_original',
       'Ant_consultor_original_retirado', 'Agencia_Original', 'ingresos',
       'egresos', 'activos', 'genero', 'Edad', 'Juridico', 'total_mora',
       'NBS_mORA', 'Total_Activas', 'NBS_Vigente', 'frecuencia_pago',
       'estado_Final_pol', 'Validacion_Mora', 'Estado_final_3_meses_atras',
       'Estado_Final_2_meses_atras', 'Estado_Final_1_mes_despues',
       'Estado_Final_2_meses_despues', 'Estado_Final_4_meses_despues',
       'efectivo_disponible'],
      dtype='object')

restar ingresos y egresos para tener efectivo displonible

In [72]:
filtered["efectivo_disponible"] = filtered["ingresos"] - filtered["egresos"]

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\336506983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["efectivo_disponible"] = filtered["ingresos"] - filtered["egresos"]

In [79]:
filtered.drop(columns = ['Corte','id_pol','Prestamos', 'Ant_consultor_original',
       'Ant_consultor_original_retirado','Agencia_Original',  'frecuencia_pago','estado_Final_pol','Validacion_Mora',
       'Estado_Final_4_meses_despues', "ingresos", "egresos"], inplace=True)

In [93]:
filtered.drop(columns = ['Estado_Final_1_mes_despues'], inplace=True)

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\4010639197.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.drop(columns = ['Estado_Final_1_mes_despues'], inplace=True)

In [94]:
filtered

,dias_mora,Estado_Inicial,Plan_Agrupado,Ant_pol,NBS,Rehabilitada,Huerfano,MedioPago,garantizado,activos,...,Juridico,total_mora,NBS_mORA,Total_Activas,NBS_Vigente,Estado_final_3_meses_atras,Estado_Final_2_meses_atras,Estado_Final_2_meses_despues,efectivo_disponible,test
0,17,3.Mora <=30,Vida Entera,317,1198163,<NA>,1,MANUAL,<NA>,0.0,...,0,1,1198163,1,1198163,<NA>,1.Al dia,3.Mora <=30,0.0,0
1,-29,1.Al dia,Temporal,290,1056296,<NA>,<NA>,AUTOMATICO,<NA>,0.0,...,0,2,1774282,2,1774282,1.Al dia,1.Al dia,1.Al dia,0.0,0
2,-22,1.Al dia,AP,314,364493,<NA>,1,AUTOMATICO,<NA>,80000000.0,...,0,3,5250399,3,5250399,1.Al dia,1.Al dia,1.Al dia,6200000.0,0
3,-14,1.Al dia,AP,299,696918,<NA>,1,AUTOMATICO,<NA>,0.0,...,0,1,696918,1,662470,1.Al dia,1.Al dia,1.Al dia,0.0,0
4,0,1.Al dia,AP,295,695639,<NA>,<NA>,AUTOMATICO,<NA>,0.0,...,0,1,695639,1,695639,<NA>,1.Al dia,<NA>,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110140,32,4.Mora <=60,PUF,6,6111496,<NA>,<NA>,AUTOMATICO,<NA>,261485000.0,...,0,2,10587675,2,10587675,4.Mora <=60,4.Mora <=60,4.Mora <=60,106388988.0,0
110141,-30,1.Al dia,PUF,6,5486643,<NA>,<NA>,AUTOMATICO,<NA>,258752000.0,...,0,1,5486643,1,5486643,1.Al dia,1.Al dia,1.Al dia,186789996.0,0
110142,-30,1.Al dia,Vida Entera,6,7200288,<NA>,<NA>,AUTOMATICO,<NA>,24028754.0,...,0,1,7200288,1,7200288,1.Al dia,1.Al dia,1.Al dia,1010567004.0,0
110143,1,3.Mora <=30,PUF,6,5490099,<NA>,<NA>,AUTOMATICO,<NA>,420000000.0,...,0,3,13680346,4,14506596,3.Mora <=30,3.Mora <=30,4.Mora <=60,122352288.0,0
110145,1,3.Mora <=30,PUF,6,6000240,<NA>,<NA>,AUTOMATICO,<NA>,231891000.0,...,0,1,6000240,1,6000240,1.Al dia,1.Al dia,3.Mora <=30,85056000.0,0

In [71]:
filtered['Plan_Agrupado'].value_counts()

Plan_Agrupado
AP                 39755
Vida Entera        22726
PUF                10220
Temporal            9764
MetLife Pension     7518
PALP                5070
Dotal               1822
Variable Life       1129
Life Cover Plus       33
Name: count, dtype: Int64

In [77]:
filtered.isna().sum()

Corte                                  0
id_pol                                 0
dias_mora                              0
Estado_Inicial                         0
Plan_Agrupado                          0
Ant_pol                                0
NBS                                    0
Rehabilitada                       96092
Huerfano                           48170
MedioPago                              0
garantizado                        97485
Prestamos                          97878
Ant_consultor_original             13876
Ant_consultor_original_retirado    54974
Agencia_Original                   13878
ingresos                               3
egresos                                3
activos                                3
genero                                 3
Edad                                   3
Juridico                               0
total_mora                             0
NBS_mORA                               0
Total_Activas                          5
NBS_Vigente                            5
frecuencia_pago                        0
estado_Final_pol                       0
Validacion_Mora                        0
Estado_final_3_meses_atras          1869
Estado_Final_2_meses_atras           329
Estado_Final_1_mes_despues          1044
Estado_Final_2_meses_despues        3745
Estado_Final_4_meses_despues        3654
efectivo_disponible                    3
dtype: int64

Cambiar estados, 1 si es nulo o mayor de 60(cancelado), de lo contrario 0 (activo), remover productos que comenzaron el mes cancelados

In [89]:
filtered['Estado_Inicial'].value_counts()

Estado_Inicial
1.Al dia       85258
3.Mora <=30     8640
4.Mora <=60     3598
5.Mayor 60       541
Name: count, dtype: Int64

In [90]:
filtered = filtered.query( " Estado_Inicial != '5.Mayor 60'")

In [96]:
filtered['Estado_Inicial'].value_counts()

Estado_Inicial
1.Al dia       85258
3.Mora <=30     8640
4.Mora <=60     3598
Name: count, dtype: Int64

In [98]:
filtered.columns

Index(['dias_mora', 'Estado_Inicial', 'Plan_Agrupado', 'Ant_pol', 'NBS',
       'Rehabilitada', 'Huerfano', 'MedioPago', 'garantizado', 'activos',
       'genero', 'Edad', 'Juridico', 'total_mora', 'NBS_mORA', 'Total_Activas',
       'NBS_Vigente', 'Estado_final_3_meses_atras',
       'Estado_Final_2_meses_atras', 'Estado_Final_2_meses_despues',
       'efectivo_disponible', 'test'],
      dtype='object')

In [102]:
filtered["Estado_Inicial"] = np.where(filtered["Estado_Inicial"].isna() | (filtered["Estado_Inicial"] == "5.Mayor 60"),1,0)
filtered['Estado_final_3_meses_atras'] = np.where(filtered['Estado_final_3_meses_atras'].isna() | (filtered['Estado_final_3_meses_atras'] == "5.Mayor 60"),1,0)
filtered["Estado_Final_2_meses_atras"] = np.where(filtered[ 'Estado_Final_2_meses_atras'].isna() | (filtered[ 'Estado_Final_2_meses_atras'] == "5.Mayor 60"),1,0)
filtered["Estado_Final_2_meses_despues"] = np.where(filtered['Estado_Final_2_meses_despues'].isna() | (filtered['Estado_Final_2_meses_despues'] == "5.Mayor 60"),1,0)

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\3804373003.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Estado_Inicial"] = np.where(filtered["Estado_Inicial"].isna() | (filtered["Estado_Inicial"] == "5.Mayor 60"),1,0)
C:\Users\juank\AppData\Local\Temp\ipykernel_7940\3804373003.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Estado_final_3_meses_atras'] = np.where(filtered['Estado_final_3_meses_atras'].isna() | (filtered['Estado_final_3_meses_atras'] == "5.Mayor 60"),1,0)
C:\Users\juank\AppData\Local\Temp\ipykernel_7940\3804373003.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Estado_Final_2_meses_atras"] = np.where(filtered[ 'Estado_Final_2_meses_atras'].isna() | (filtered[ 'Estado_Final_2_meses_atras'] == "5.Mayor 60"),1,0)
C:\Users\juank\AppData\Local\Temp\ipykernel_7940\3804373003.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered["Estado_Final_2_meses_despues"] = np.where(filtered['Estado_Final_2_meses_despues'].isna() | (filtered['Estado_Final_2_meses_despues'] == "5.Mayor 60"),1,0)

In [105]:
filtered['Estado_final_3_meses_atras'].value_counts()

Estado_final_3_meses_atras
0    97496
Name: count, dtype: int64

In [106]:
filtered2 = df[df["Corte"].dt.normalize() == pd.Timestamp("2025-01-01") ].copy()

In [108]:
filtered2['Estado_final_3_meses_atras'].value_counts()

Estado_final_3_meses_atras
1.Al dia           79872
3.Mora <=30        10064
2.Pendiente_Mes     7736
4.Mora <=60         3425
5.Mayor 60           381
Name: count, dtype: Int64

eliminamos los estados de los meses anteriores ya que todos los productos estaban activos tambien los meses anteriores

In [109]:
filtered.drop(columns=['Estado_final_3_meses_atras',
       'Estado_Final_2_meses_atras'], inplace = True)

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\1449929432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.drop(columns=['Estado_final_3_meses_atras',

In [111]:
filtered

,dias_mora,Estado_Inicial,Plan_Agrupado,Ant_pol,NBS,Rehabilitada,Huerfano,MedioPago,garantizado,activos,...,Edad,Juridico,total_mora,NBS_mORA,Total_Activas,NBS_Vigente,Estado_Final_2_meses_despues,efectivo_disponible,test,'Estado_Final_2_meses_despues'
0,17,0,Vida Entera,317,1198163,<NA>,1,MANUAL,<NA>,0.0,...,78,0,1,1198163,1,1198163,0,0.0,0,0
1,-29,0,Temporal,290,1056296,<NA>,<NA>,AUTOMATICO,<NA>,0.0,...,54,0,2,1774282,2,1774282,0,0.0,0,0
2,-22,0,AP,314,364493,<NA>,1,AUTOMATICO,<NA>,80000000.0,...,63,0,3,5250399,3,5250399,0,6200000.0,0,0
3,-14,0,AP,299,696918,<NA>,1,AUTOMATICO,<NA>,0.0,...,63,0,1,696918,1,662470,0,0.0,0,0
4,0,0,AP,295,695639,<NA>,<NA>,AUTOMATICO,<NA>,0.0,...,56,0,1,695639,1,695639,1,0.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110140,32,0,PUF,6,6111496,<NA>,<NA>,AUTOMATICO,<NA>,261485000.0,...,38,0,2,10587675,2,10587675,0,106388988.0,0,0
110141,-30,0,PUF,6,5486643,<NA>,<NA>,AUTOMATICO,<NA>,258752000.0,...,45,0,1,5486643,1,5486643,0,186789996.0,0,0
110142,-30,0,Vida Entera,6,7200288,<NA>,<NA>,AUTOMATICO,<NA>,24028754.0,...,64,0,1,7200288,1,7200288,0,1010567004.0,0,0
110143,1,0,PUF,6,5490099,<NA>,<NA>,AUTOMATICO,<NA>,420000000.0,...,42,0,3,13680346,4,14506596,0,122352288.0,0,0
110145,1,0,PUF,6,6000240,<NA>,<NA>,AUTOMATICO,<NA>,231891000.0,...,40,0,1,6000240,1,6000240,0,85056000.0,0,0

In [121]:
filtered.columns

Index(['dias_mora', 'Estado_Inicial', 'Plan_Agrupado', 'Ant_pol', 'NBS',
       'Rehabilitada', 'Huerfano', 'MedioPago', 'garantizado', 'activos',
       'genero', 'Edad', 'Juridico', 'total_mora', 'NBS_mORA', 'Total_Activas',
       'NBS_Vigente', 'Estado_Final_2_meses_despues', 'efectivo_disponible',
       'test', 'Estado_Final_2_meses_despues'],
      dtype='object')

In [120]:
filtered.rename(columns = {"'Estado_Final_2_meses_despues'" : 'Estado_Final_2_meses_despues'}, inplace = True)

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\2171825676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.rename(columns = {"'Estado_Final_2_meses_despues'" : 'Estado_Final_2_meses_despues'}, inplace = True)

In [133]:
filtered.isna().sum()

dias_mora                       0
Estado_Inicial                  0
Plan_Agrupado                   0
Ant_pol                         0
NBS                             0
Huerfano                        0
MedioPago                       0
activos                         0
genero                          0
Edad                            0
Juridico                        0
total_mora                      0
NBS_mORA                        0
Total_Activas                   0
NBS_Vigente                     0
Estado_Final_2_meses_despues    0
efectivo_disponible             0
Estado_Final_2_meses_despues    0
dtype: int64

Rehabilitada y huerfano tien muy pocos valores en 1, se eliminaran

In [125]:
filtered['Rehabilitada'].value_counts()

Rehabilitada
1    1926
Name: count, dtype: Int64

In [127]:
filtered.drop(columns= ['Rehabilitada', 'garantizado', 'test'], inplace = True)

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\2020800883.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.drop(columns= ['Rehabilitada', 'garantizado', 'test'], inplace = True)

In [128]:
filtered

,dias_mora,Estado_Inicial,Plan_Agrupado,Ant_pol,NBS,Huerfano,MedioPago,activos,genero,Edad,Juridico,total_mora,NBS_mORA,Total_Activas,NBS_Vigente,Estado_Final_2_meses_despues,efectivo_disponible,Estado_Final_2_meses_despues
0,17,0,Vida Entera,317,1198163,1,MANUAL,0.0,F,78,0,1,1198163,1,1198163,0,0.0,0
1,-29,0,Temporal,290,1056296,<NA>,AUTOMATICO,0.0,,54,0,2,1774282,2,1774282,0,0.0,0
2,-22,0,AP,314,364493,1,AUTOMATICO,80000000.0,F,63,0,3,5250399,3,5250399,0,6200000.0,0
3,-14,0,AP,299,696918,1,AUTOMATICO,0.0,M,63,0,1,696918,1,662470,0,0.0,0
4,0,0,AP,295,695639,<NA>,AUTOMATICO,0.0,F,56,0,1,695639,1,695639,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110140,32,0,PUF,6,6111496,<NA>,AUTOMATICO,261485000.0,F,38,0,2,10587675,2,10587675,0,106388988.0,0
110141,-30,0,PUF,6,5486643,<NA>,AUTOMATICO,258752000.0,F,45,0,1,5486643,1,5486643,0,186789996.0,0
110142,-30,0,Vida Entera,6,7200288,<NA>,AUTOMATICO,24028754.0,M,64,0,1,7200288,1,7200288,0,1010567004.0,0
110143,1,0,PUF,6,5490099,<NA>,AUTOMATICO,420000000.0,F,42,0,3,13680346,4,14506596,0,122352288.0,0
110145,1,0,PUF,6,6000240,<NA>,AUTOMATICO,231891000.0,M,40,0,1,6000240,1,6000240,0,85056000.0,0

Llenar nulls de huerfano con 0 (no son huerfanos)

In [130]:
filtered['Huerfano'] = filtered['Huerfano'].fillna(0)

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\1904892699.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered['Huerfano'] = filtered['Huerfano'].fillna(0)

Quedan muy pocos nas en las columnas los eliminaremos

In [132]:
filtered.dropna(how="any", inplace = True)

C:\Users\juank\AppData\Local\Temp\ipykernel_7940\2875630188.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered.dropna(how="any", inplace = True)

In [135]:
filtered

,dias_mora,Estado_Inicial,Plan_Agrupado,Ant_pol,NBS,Huerfano,MedioPago,activos,genero,Edad,Juridico,total_mora,NBS_mORA,Total_Activas,NBS_Vigente,Estado_Final_2_meses_despues,efectivo_disponible,Estado_Final_2_meses_despues
0,17,0,Vida Entera,317,1198163,1,MANUAL,0.0,F,78,0,1,1198163,1,1198163,0,0.0,0
1,-29,0,Temporal,290,1056296,0,AUTOMATICO,0.0,,54,0,2,1774282,2,1774282,0,0.0,0
2,-22,0,AP,314,364493,1,AUTOMATICO,80000000.0,F,63,0,3,5250399,3,5250399,0,6200000.0,0
3,-14,0,AP,299,696918,1,AUTOMATICO,0.0,M,63,0,1,696918,1,662470,0,0.0,0
4,0,0,AP,295,695639,0,AUTOMATICO,0.0,F,56,0,1,695639,1,695639,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110140,32,0,PUF,6,6111496,0,AUTOMATICO,261485000.0,F,38,0,2,10587675,2,10587675,0,106388988.0,0
110141,-30,0,PUF,6,5486643,0,AUTOMATICO,258752000.0,F,45,0,1,5486643,1,5486643,0,186789996.0,0
110142,-30,0,Vida Entera,6,7200288,0,AUTOMATICO,24028754.0,M,64,0,1,7200288,1,7200288,0,1010567004.0,0
110143,1,0,PUF,6,5490099,0,AUTOMATICO,420000000.0,F,42,0,3,13680346,4,14506596,0,122352288.0,0
110145,1,0,PUF,6,6000240,0,AUTOMATICO,231891000.0,M,40,0,1,6000240,1,6000240,0,85056000.0,0

In [145]:
filtered['Edad'].value_counts().sort_index()

Edad
19     4
20    11
21    14
22    27
23    43
      ..
82     3
83     1
84     3
85     1
88     3
Name: count, Length: 68, dtype: Int64

En edad, eliminar registros con menos de 18 anios y mas de 100 anios

In [144]:
filtered = filtered[(filtered["Edad"] >= 18) & (filtered["Edad"] <= 100)]

In [154]:
filtered['Estado_Final_2_meses_despues'].value_counts()

Estado_Final_2_meses_despues
0    86504
1     4056
Name: count, dtype: int64

In [151]:
filtered = filtered.loc[:, ~filtered.columns.duplicated()]

In [152]:
filtered.columns

Index(['dias_mora', 'Estado_Inicial', 'Plan_Agrupado', 'Ant_pol', 'NBS',
       'Huerfano', 'MedioPago', 'activos', 'genero', 'Edad', 'Juridico',
       'total_mora', 'NBS_mORA', 'Total_Activas', 'NBS_Vigente',
       'Estado_Final_2_meses_despues', 'efectivo_disponible'],
      dtype='object')

Arreglar problemas en la columna genero

In [165]:
filtered['genero'] = filtered['genero'].str.strip()

filtered = filtered[filtered['genero'].isin(['M','F'])]

In [166]:
filtered['genero'].value_counts()

genero
M    47298
F    33588
Name: count, dtype: int64

In [167]:
filtered['Estado_Final_2_meses_despues'].value_counts()

Estado_Final_2_meses_despues
0    77234
1     3652
Name: count, dtype: int64

In [172]:
filtered.to_parquet(
    "filtered_base.parquet",
    engine="pyarrow",    
    index=False,         
    compression="snappy" 
)

In [171]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\juank\anaconda3\lib\site-packages (11.0.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\juank\anaconda3\lib\site-packages (from pyarrow) (1.26.4)
Note: you may need to restart the kernel to use updated packages.